### ISSUE TITLE
No prompt display

### ISSUE THREAD

**Issue by ol1vegr0ve** [jackomix/questsim#1]
![image_2023-10-11_141418007](https://github.com/jackomix/questsim/assets/97995086/c80f8d37-cfbc-4ec2-a1a7-c453131ccf6f)
Happens randomly when waiting on queue

**Comment by jackomix** [comment]
considering the choices are different, my guess is the AI only wrote whitespace in the prompt display. i've updated the code to remove whitespaces to check if the prompt display is truly empty. so hopefully this issue should be fixed.
